title: ìµœì†Œì€ ì‚¬ì´íŠ¸
name: ìµœì†Œì€
email: 980407cse@gmail.com
description: >-
  Data Scientist & A.I developer


baseurl: ""
url: "https://choisoeungitblog.github.io"


# profile ì´ë¯¸ì§€
profile_image: images/about1.jpg


# SNS ì•„ì´ë””
instagram_id: https://www.instagram.com/so_euneun


# Youtube vid
youtube_vid: #


# Custom Color
primary: b72cf0
primary_hover: ec5453
color_1: 2c98f0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (í…ìŠ¤íŠ¸ê°€ ìš°ì¸¡ ì •ë ¬ëœ ìŠ¬ë¼ì´ë”)
slider_0: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- background_url: images/cover_bg_4.jpg
  title: Choi So Eun <br> portfolio site</br> 
  subtitle: >- 
    ë‹¨ìˆœí•œ í˜¸ê¸°ì‹¬ì—ì„œ ëë‚˜ì§€ ì•Šê³ <br>
    ê¾¸ì¤€íˆ ë°œì „ì‹œí‚¤ê³ ì<br>
    ë¬´ì‘ì • ë”°ë¼í•˜ë©° ì„±ì¥í•˜ëŠ”<br>
    ê°œë°œì ìµœì†Œì€ì…ë‹ˆë‹¤.
  position: absolute
  transform: translate( -50%, -50% )
  left: 200px
  bottom: 80px

# slider type 1  (í…ìŠ¤íŠ¸ê°€ ì¢Œì¸¡ ì •ë ¬ëœ ìŠ¬ë¼ì´ë”)
slider_1: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- background_url: images/img_bg_4.jpg
  title: I am<br>AI Developer
  subtitle: >- 
    ë‹¨ìˆœí•œ í˜¸ê¸°ì‹¬ì—ì„œ ëë‚˜ì§€ ì•Šê³ <br>
    ê¾¸ì¤€íˆ ë°œì „ì‹œí‚¤ê³ ì<br>
    ë¬´ì‘ì • ë”°ë¼í•˜ë©° ì„±ì¥í•˜ëŠ”<br>
    ê°œë°œì ìµœì†Œì€ì…ë‹ˆë‹¤.
  position: absolute
  transform: translate( -50%, -50% )
  left: 400px
  bottom: 280px


# About
about_meta: About Me
about_header: >- 
  "í˜¸ê¸°ì‹¬ ë§ì€ ëŒ€í•™ìƒ"
about_introduce: >-
  "ì•ˆë…•í•˜ì„¸ìš”. í’€ìŠ¤íƒ ì „ë¬¸ê°€ë¥¼ ê¿ˆê¾¸ëŠ” ë”°ë¼ìŸì´ ê°œë°œìì…ë‹ˆë‹¤."
  <br> Choisoeun siteë¥¼ ìš´ì˜í•˜ëŠ” ì¤‘ì…ë‹ˆë‹¤.ğŸ’»</br>



about_content: >-

  <br><strong>ğŸ’¡ì•„ë¬´ê²ƒë„ ëª°ëì„ë•Œ ë”°ë¼í•˜ë©´ì„œ ë°°ì›Œë³´ìë¼ëŠ” ìƒê°ìœ¼ë¡œ ğŸ”ë”°ë¼ìŸì´ğŸ”ë¼ ì§€ì—ˆìŠµë‹ˆë‹¤.ğŸ’¡</strong></br>
  <br><strong>ì œ ğŸ‘€**ê´€ì‹¬ë¶„ì•¼**ëŠ” ë‹¤ìŒê³¼ ê°™ìŠµë‹ˆë‹¤. <strong></br>
  <br> ğŸ“‹ Machine Learning, Deep Learning </br>
  <br><strong>ì €ì—ê²Œ ì¡°ê¸ˆ ê´€ì‹¬ì´ ìƒê¸°ì…¨ë‹¤ë©´ [CV](/images/cv.pdf)ë¥¼ í™•ì¸í•´ì£¼ì‹œë©´ ê°ì‚¬í•˜ê² ìŠµë‹ˆë‹¤!ğŸ˜ƒ</strong></br>
  <br>ê°œë°œì— ê´€ì‹¬ì„ ê°–ê¸° ì‹œì‘í•˜ê³  ë¬´ì‘ì • ë”°ë¼í•˜ë©° ë°°ì›Œë³´ìëŠ” ë§ˆìŒìœ¼ë¡œ ì‹œì‘í•˜ê²Œ ë˜ì—ˆìŠµë‹ˆë‹¤.</br>
  <br><strong>íŒ€í”„ë¡œì íŠ¸ì™€ ê°œì¸ í”„ë¡œì íŠ¸ë¥¼ ë³‘í–‰í•˜ë©° ì˜ˆê¸°ì¹˜ ëª»í•œ ìƒí™©ì—ì„œì˜ ëŒ€ì²˜ ëŠ¥ë ¥ì„ ê¸°ë¥´ê³  ìˆìŠµë‹ˆë‹¤.</strong></br>
  <br>íŒ€í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•˜ë©° êµ¬ì„±ì›ë“¤ê³¼ì˜ í˜‘ì—…ì„ í†µí•´ ê²°ê³¼ë¬¼ì„ ë§Œë“¤ì–´ëƒˆì„ ë•Œì˜ ì„±ì·¨ê°ì€ ì´í›„ì— ë‹¤ë¥¸ í”„ë¡œì íŠ¸ë¥¼ ì§„í–‰í•˜ëŠ”ë° ì£¼ëœ ë™ê¸°ê°€ ë  ê²ƒì´ë¼ê³  ìƒê°í•©ë‹ˆë‹¤. </br>
  <br>ë˜í•œ ê°œì¸ í”„ë¡œì íŠ¸ëŠ” ìŠ¤ìŠ¤ë¡œ ê³ ë¯¼í•˜ëŠ” ì‹œê°„ì„ í†µí•´ ìì‹ ì˜ ê°œë°œ ëŠ¥ë ¥ì„ ê¸°ë¥´ëŠ”ë° ì£¼ëœ ì—­í• ì„ í•  ìˆ˜ ìˆë‹¤ê³  ìƒê°í•©ë‹ˆë‹¤.
about_services: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- icon: icon-data
  name: Server
- icon: icon-monitor
  name: Web
- icon: icon-phone3
  name: App
- icon: icon-code
  name: Python
about_box_content: <strong> Developers who are constantly challenging themselves.</strong> <br>ìƒê°í•˜ëŠ”ëŒ€ë¡œ ê°œë°œì´ í˜ëŸ¬ê°€ëŠ” ê²½ìš°ë³´ë‹¤ ê·¸ë ‡ì§€ ì•Šì€ ê²½ìš°ê°€ ë§ê¸°ì— ì´ì— ìµìˆ™í•´ì§€ê³  ëŠì„ì—†ì´ ë„ì „í•˜ëŠ” ê²ƒì´ ì¤‘ìš”í•˜ë‹¤ê³  ìƒê°í•©ë‹ˆë‹¤.</br>
about_box_button:
  link: http://github.com/soeunida
  name: ê¾¸ì¤€íˆ ë„ì „í•˜ëŠ” ê°œë°œìê°€ ë˜ê² ìŠµë‹ˆë‹¤.

about_box_content_color : rgb(255,255,255)


# Tech  skill
tech_meta: TECH SKILLS
tech_header: ì €ëŠ” í˜„ì¬ ì´ê²ƒì„ í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.
tech_content: ì €ì˜ ê´€ì‹¬ ë¶„ì•¼ ì…ë‹ˆë‹¤.
tech_list: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- name: Python
  color: color-1
  animation: fadeInLeft
  percent: 60
  mark: 60
  content: íŒŒì´ì¬ ê¸°ì´ˆ, ë°ì´í„° ë¶„ì„ê³¼ ì‹œê°í™”ë¥¼ ê³µë¶€í•˜ê³  íŒŒì´ì¬ ì–¸ì–´ì˜ ê¸°ë³¸ì ì¸ ë¬¸ë²•ì— ëŒ€í•´ ì•Œê³  ìˆìœ¼ë©°, ìë£Œêµ¬ì¡° ë° ì•Œê³ ë¦¬ì¦˜ì„ íŒŒì´ì¬ìœ¼ë¡œ ê³µë¶€í•˜ì˜€ìŠµë‹ˆë‹¤.
- name: ë”¥ëŸ¬ë‹
  color: color-2
  animation: fadeInRight
  percent: 10
  mark: 20
  content: ê³µë¶€í•˜ë©´ ê³µë¶€í• ìˆ˜ë¡ ì´ ë¶„ì•¼ê°€ ì •ë§ ë°©ëŒ€í•˜ê³  ì œê°€ ì•„ëŠ”ê²ƒì´ ì •ë§ ì¼ë¶€ë¶„ì´ë¼ëŠ” ê²ƒì„ ë§ì´ ëŠë‚ë‹ˆë‹¤. í†µê³„ ì´ë¡ ë¶€í„° ë‹¤ì‹œ ë°°ìš°ê² ë‹¤ëŠ” ë§ˆìŒìœ¼ë¡œ ê³µë¶€í•˜ê³  ìˆìŠµë‹ˆë‹¤.
- name: html
  color: color-3
  animation: fadeInLeft
  percent: 40
  mark: 40
  content: í’€ìŠ¤íƒ ì „ë¬¸ê°€ê°€ ë˜ê¸° ìœ„í•´ portfolio siteì™€ ê°™ì´ ì € ìì‹ ì„ í‘œí˜„ í•  ìˆ˜ ìˆëŠ” í”„ë¡œì íŠ¸ë¥¼ ê¸°íší•˜ê³  ì§„í–‰í•˜ê³  ìˆìŠµë‹ˆë‹¤.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 60
  mark: 60
  content: ëŒ€ë¶€ë¶„ì˜ í”„ë¡œì íŠ¸ë¥¼ githubë¥¼ í†µí•´ ì†ŒìŠ¤ ì½”ë“œë¥¼ ê´€ë¦¬í•˜ì˜€ìœ¼ë©°, í˜‘ì—… ì—­ì‹œ githubì„ í†µí•´ ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤. ë˜í•œ githubì„œë²„ë¥¼ í™œìš©í•˜ì—¬ ë¸”ë¡œê·¸ ë° í¬íŠ¸í´ë¦¬ì˜¤ ì‚¬ì´íŠ¸ë¥¼ ê´€ë¦¬í•©ë‹ˆë‹¤.
tech_desc: ì•ìœ¼ë¡œ ì—°êµ¬í•œê²ƒì„ ì„œë¹„ìŠ¤í™”í•˜ê¸° ìœ„í•´ì„œ <strong>javascript, Node JS, ë¦¬ì—‘íŠ¸, ìŠ¤í”¼ë§, í—¤ë¡œì¿ , python anywhere ë° ì•„ë§ˆì¡´ AWS, docker</strong>ë“±ì„ ê³„ì†í•´ì„œ ì¡°ê¸ˆì”© ê³µë¶€í•  ìƒê°ì…ë‹ˆë‹¤. 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: ì €ì˜ ê°œì¸ í”„ë¡œì íŠ¸ì™€ íŒ€í”„ë¡œì íŠ¸ë¥¼ ì†Œê°œí•˜ê² ìŠµë‹ˆë‹¤.
project_load_more: ì•ìœ¼ë¡œ ë” ë§ì€ í”„ë¡œì íŠ¸ê°€ ì¶”ê°€ë  ì˜ˆì •ì…ë‹ˆë‹¤:)    # ë”ë³´ê¸° ë‚´ìš©
project_load_more_url: http://github.com/soeunida

project_my_name: ê°œì¸í”„ë¡œì íŠ¸

project_my: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- background_url: images/personal_project1.jpg
  animation: fadeInLeft
  name: tensorflowë¥¼ ì´ìš©í•œ ìì—°ì–´ ì²˜ë¦¬(2021.07)
  description: 8ì£¼ê°„ì˜ ìì—°ì–´ ì²˜ë¦¬ êµìœ¡ì„ ìˆ˜ê°•í•˜ë©°, ì§ì ‘ Wordembedding, RNN,CNN, Classification, Text Similarity, SPAMë¶„ë¥˜, POS Tagging, NER ëª¨ë¸ì„ ê³µë¶€í•˜ì˜€ìŠµë‹ˆë‹¤.ìì—°ì–´ë¥¼ ë¶„ì„í•˜ì—¬ ì¸ê³µì–´ë¡œ ì²˜ë¦¬í•˜ëŠ” ê¸°ìˆ ì´ ë§ˆì¹˜ ì¸ê°„ê³¼ ì»´í“¨í„° ì‚¬ì´ì˜ í†µì—­ì‚¬ ê°™ì€ ì—­í• ì„ í•˜ëŠ” ê²ƒ ê°™ì•˜ìŠµë‹ˆë‹¤. í”„ë¡œì íŠ¸ë¥¼ ìˆ˜í–‰í•˜ë©° MODELINGê³¼ì •ì—ì„œ ê²ªì—ˆë˜ ì–´ë ¤ì›€ì— ëŒ€í•´ ë”ìš± ê¹Šì´ ìˆëŠ” ê³ ì°°ì„ ìœ„í•´ tensorflow í™œìš©ê³¼ ë¦¬ëˆ…ìŠ¤, í•˜ë‘¡ì— ëŒ€í•œ ì´ë¡  ì§€ì‹ í•™ìŠµì„ ìœ„í•´ í•¨ê»˜ êµìœ¡ì„ ì§„í–‰í–ˆë˜ ì‚¬ëŒë“¤ê³¼ ìŠ¤í„°ë””ë¥¼ ì§„í–‰ì¤‘ì…ë‹ˆë‹¤. 
  detail_url: images/personal_project11.pdf
  readmore_url: images/personal_project11.pdf

- background_url: images/blog-1.jpg
  animation: fadeInLeft
  name: ê°œì¸ í”„ë¡œì íŠ¸ GITBLOG(2021.12)
  description: Githubì— ì˜¬ë ¤ë†“ì€ ì½”ë“œë‚˜ ê³ ë¯¼ì˜ ê³¼ì •ë“¤ì„ ë” ë§ì€ ì‚¬ëŒë“¤ì—ê²Œ ê³µìœ í•˜ê³ ì gitblogë¥¼ ë§Œë“¤ê²Œ ë˜ì—ˆìŠµë‹ˆë‹¤. HTMLê³¼ JAVAê¸°ë°˜ìœ¼ë¡œ ê°œë°œ í•˜ì˜€ìŠµë‹ˆë‹¤.
  detail_url: images/blog-11.pdf
  readmore_url: images/blog-11.pdf

project_team_name: íŒ€í”„ë¡œì íŠ¸
project_team: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- background_url: images/team_project3.jpg
  animation: fadeInRight
  name: í™˜ê²½ì ë¦½ê¸ˆê´€ë¦¬ ì–´í”Œë¦¬ì¼€ì´ì…˜ ê¸°íš(2020.05)
  description: <br>ê¸°ì—…,í™˜ê²½ë‹¨ì²´,ê³ ê°ì„ ëŒ€ìƒìœ¼ë¡œ ì„œë¡œì˜ ìƒê´€ê´€ê³„ íŒŒì•… í›„, ì¤‘ê°„ì ì…ì¥ì—ì„œ ì´ìµì„ ì°½ì¶œí•˜ê¸° ìœ„í•´ ê³ ë¯¼í•˜ê³  ì–´í”Œë¦¬ì¼€ì´ì…˜ì„ ê¸°íší•˜ì˜€ìŠµë‹ˆë‹¤.</br>ì´ íŒ€í”„ë¡œì íŠ¸ì—ì„œ SQLì„ ì´ìš©í•œ Dateê´€ë¦¬ì™€ figmaë¥¼ ì´ìš©í•œ UIê°œë°œ ë¶„ì•¼ë¥¼ ë‹´ë‹¹í•˜ì˜€ìŠµë‹ˆë‹¤.
  detail_url: images/team_project33.pdf
  readmore_url: images/team_project33.pdf

project_business_name: Business
project_business: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- background_url: images/img_bg_5.jpg
  animation: fadeInRight
  name: Data mining Labì†Œì† í•™ë¶€ì—°êµ¬ìƒ(2022.01)
  description: <br>ì†Œì† ì—°êµ¬ì‹¤ì—ì„œ Deep learningì„ ì´ìš©í•œ Lap seminarë¥¼ ì§„í–‰í•˜ë©° ë”ìš± ê¹Šì´ ìˆëŠ” ê³ ì°°ì„ ì§„í–‰í•  ìˆ˜ ìˆì—ˆìŠµë‹ˆë‹¤.</br>
  detail_url: https://sites.google.com/view/dmininglab/home
  readmore_url: https://sites.google.com/view/dmininglab/home



# Experience
exp_meta: What have I achieved?
exp_header: ì €ëŠ” ì´ëŸ° "ê²½í—˜"ë“¤ì„ í•´ë´¤ìŠµë‹ˆë‹¤.
exp_content: ë‹¨ìˆœíˆ ê°œë°œë¡œì„œë¿ë§Œ ì•„ë‹ˆë¼ ë‹¤ë¥¸ ì‚¬ëŒë“¤ê³¼ í•¨ê»˜ í˜‘ì—…í•˜ì—¬ ë¬¸ì œë¥¼ í•´ê²°í•˜ëŠ” ëŠ¥ë ¥ì„ ê·¹ëŒ€í™” ì‹œí‚¬ ìˆ˜ ìˆëŠ” ì €ì˜ ì¥ì ì…ë‹ˆë‹¤. 
exp_services: # í˜•ì‹ì— ë§ì¶”ì–´ í•­ëª© ì¶”ê°€
- name: ì ê·¹ì ì¸ ì†Œí†µê³¼ í˜‘ì—… ëŠ¥ë ¥
  color: color-1
  icon: icon-bulb
  content: íŒ€ í”„ë¡œì íŠ¸ì—ì„œ ì ê·¹ì ì¸ ì˜ì‚¬ ì†Œí†µìœ¼ë¡œ ì„œë¡œì˜ ì´í•´ê´€ê³„ë¥¼ íŒŒì•…í•˜ê³  ì˜ê²¬ì„ ì¡°ìœ¨í•˜ëŠ” ê²ƒì— ìµìˆ™í•©ë‹ˆë‹¤. 
- name: ë©ˆì¶”ì§€ ì•ŠëŠ” ë„ì „ì •ì‹ 
  color: color-2
  icon: icon-home
  content: ì œê°€ ì„ íƒí•œ ê¸¸, í•­ìƒ ì—´ì •ì„ ë‹¤í•´ ê³µë¶€í•˜ë©° ìƒˆë¡œìš´ ê¸°ìˆ ì— ëŒ€í•´ ì¦ê±°ìš´ ë§ˆìŒìœ¼ë¡œ ë°°ì›ë‹ˆë‹¤.
- name: í•„ìš”ì— ì˜í•œ í”„ë¡œì íŠ¸ ì§„í–‰
  color: color-3
  icon: icon-phone3
  content: ìŠ¤ìŠ¤ë¡œ í•„ìš”ì„±ì„ ëŠë¼ëŠ” ë‹¤ì–‘í•œ í”„ë¡œì íŠ¸ë¥¼ ê¸°íš, ì§„í–‰ í•´ì™”ê¸°ì— ì—…ë¬´ì— ìˆì–´ì„œë„ ìƒˆë¡œìš´ í”„ë¡œì íŠ¸ì— ë„ì „ì ì…ë‹ˆë‹¤.
exp_counters:
- name: Online Class Sales
  count: 344
  speed: 10000
- name: project
  count: 6
  speed: 5000


# certificate
certificate_meta: Certificate
certificate_header: Certificate
blog_load_more: ë” ë°œì „í•˜ê¸° ìœ„í•´ í•­ìƒ ë…¸ë ¥í•©ë‹ˆë‹¤    # ë”ë³´ê¸° ë‚´ìš©
certificate_list:
- title: ì •ë³´ì²˜ë¦¬ì‚°ì—…ê¸°ì‚¬
  subtitle: ì‚°ì—…ì¸ë ¥ê³µë‹¨
  date: 2018.03.16 - 2018.11
  content: ìê²©ë²ˆí˜¸  18203101837R 
  thumbnail_url: images/img_bg_6.jpg

- title: ë„¤íŠ¸ì›Œí¬ê´€ë¦¬ì‚¬2ê¸‰
  subtitle: í•œêµ­ì •ë³´í†µì‹ ìê²©í˜‘íšŒ
  date: 2017.07.01 - 2017.12.19
  content:  ìê²©ë²ˆí˜¸  NT2040627
  thumbnail_url: images/certificate_bg.png


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: KYONGGI UNIVERSITY 
  subtitle: ê²½ê¸°ëŒ€ ì‚°ì—…ê²½ì˜ê³µí•™ê³¼
  date: 2019.01 - í˜„ì¬
  content: AI , backend&frontend ê³µë¶€ ì¤‘
  date: 2019.03 - 2023.02
  content: ì‚¬ëŒê³¼ ê¸°ê³„ë¥¼ ì—°ê²°í•˜ëŠ” ì‚°ì—…ê³µí•™ì— í¥ë¯¸ê°€ ìƒê¸°ê¸° ì‹œì‘í–ˆìŠµë‹ˆë‹¤.
- title: Kyungan HIGH SCHOOL
  subtitle: ê²½ì•ˆê³ ë“±í•™êµ
  date: 2014.03 - 2017.02
  content: >-





# Blog
blog_meta: self-improvement
blog_header: GITHUB
blog_load_more: ë” ë°œì „í•˜ê¸° ìœ„í•´ í•­ìƒ ë…¸ë ¥í•©ë‹ˆë‹¤    # ë”ë³´ê¸° ë‚´ìš©
blog_load_more_url: http://github.com/soeunida
blog_list:
- title: í˜¸ê¸°ì‹¬ ëŒ€í•™ìƒì˜ Github
  subtitle: ê°œë°œ github ìš´ì˜
  date: 2021.12
  content: ì—¬ëŸ¬ ë¶„ì•¼ì˜ í”„ë¡œê·¸ë˜ë¨¸ë“¤ì„ ë³´ë©´ì„œ ë¶€ëŸ¬ì›Œë„ í•˜ê³  ì¢Œì ˆë„ í•˜ì˜€ì§€ë§Œ í¬ê¸°í•˜ì§€ì•Šê³  ì–´ëŠ í•œë¶„ì•¼ë¼ë„ 'ì¥ì¸'ì´ ë˜ê² ë‹¤ëŠ” ë§ˆìŒìœ¼ë¡œ ê¾¸ì¤€íˆ ê°œë°œ githubë¥¼ ìš´ì˜í•´ì˜¤ê³  ìˆìŠµë‹ˆë‹¤.
  thumbnail_url: images/blog-4.jpg
  link: http://github.com/soeunida



# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: 980407cse@gmail.com
  icon: icon-globe-outline
- title: ê²½ê¸°ë„ ì•ˆì‚°ì‹œ 
  icon: icon-map
- title: +82 10 xxxx xxxx
  icon: icon-phone
- title: Github
  icon: icon-layers2
  url: https://github.com/soeunida/portfolio
contact_message: <em>ì—°ë½í•´ì£¼ì…”ì„œ ê°ì‚¬í•©ë‹ˆë‹¤.</em> 24ì‹œê°„ì´ë‚´ì— íšŒì‹ ë“œë¦¬ë„ë¡ í•˜ê² ìŠµë‹ˆë‹¤. :)


optional_front_matter:
  remove_originals:    true
